version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo test
      - echo $(docker --version)
      - $(aws ecr get-login --region us-west-1 --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - docker build -t nginx1 .
      - docker tag nginx1:latest $ECR_REPOSITORY_URI:latest
      - docker push $ECR_REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`